import { Employee } from "../../types";

export const MOCK_EMPLOYEES: Employee[] = [
    { "Id": 1, "Name": "George Smith", "Title": "Chief Executive Officer (CEO)", "ManagerId": null },
    { "Id": 2, "Name": "Michael Johnson", "Title": "Chief Financial Officer (CFO)", "ManagerId": 1 },
    { "Id": 3, "Name": "Sarah Williams", "Title": "Chief Technology Officer (CTO)", "ManagerId": 1 },
    { "Id": 4, "Name": "Emma Brown", "Title": "Finance Manager", "ManagerId": 2 },
    { "Id": 5, "Name": "John Davis", "Title": "Technology Manager", "ManagerId": 3 },
    { "Id": 6, "Name": "Sophia Miller", "Title": "Accountant", "ManagerId": 4 },
    { "Id": 7, "Name": "Chris Wilson", "Title": "Software Engineer", "ManagerId": 5 },
    { "Id": 8, "Name": "Ella Moore", "Title": "Quality Assurance Engineer", "ManagerId": 5 },
    { "Id": 9, "Name": "David Taylor", "Title": "Software Intern", "ManagerId": 7 },
    { "Id": 10, "Name": "Liam Anderson", "Title": "IT Support Specialist", "ManagerId": 8 },
    { "Id": 11, "Name": "Emily Thomas", "Title": "Financial Analyst", "ManagerId": 4 },
    { "Id": 12, "Name": "Lucas Martinez", "Title": "Backend Developer", "ManagerId": 7 },
    { "Id": 13, "Name": "Charlotte Garcia", "Title": "Frontend Developer", "ManagerId": 7 },
    { "Id": 14, "Name": "James White", "Title": "DevOps Engineer", "ManagerId": 5 },
    { "Id": 15, "Name": "Oliver Harris", "Title": "Product Manager", "ManagerId": 3 },
    { "Id": 16, "Name": "Isabella Clark", "Title": "UX Designer", "ManagerId": 15 },
    { "Id": 17, "Name": "Benjamin Lewis", "Title": "Project Manager", "ManagerId": 2 },
    { "Id": 18, "Name": "Sophia Hall", "Title": "Business Analyst", "ManagerId": 17 },
    { "Id": 19, "Name": "Alexander Young", "Title": "Data Scientist", "ManagerId": 3 },
    { "Id": 20, "Name": "Ava Scott", "Title": "Customer Success Manager", "ManagerId": 19 },
    { "Id": 21, "Name": "Ethan Green", "Title": "Sales Manager", "ManagerId": 1 },
    { "Id": 22, "Name": "Mia Adams", "Title": "Sales Representative", "ManagerId": 21 },
    { "Id": 23, "Name": "Harper Hill", "Title": "Account Manager", "ManagerId": 21 },
    { "Id": 24, "Name": "Jack Nelson", "Title": "HR Manager", "ManagerId": 1 },
    { "Id": 25, "Name": "Amelia Baker", "Title": "Recruitment Specialist", "ManagerId": 24 },
    { "Id": 26, "Name": "Henry Rivera", "Title": "Compensation Specialist", "ManagerId": 24 },
    { "Id": 27, "Name": "Grace Campbell", "Title": "Training Specialist", "ManagerId": 24 },
    { "Id": 28, "Name": "Lucas Mitchell", "Title": "IT Support", "ManagerId": 5 },
    { "Id": 29, "Name": "Elijah Perez", "Title": "Mobile Developer", "ManagerId": 5 },
    { "Id": 30, "Name": "Emily Roberts", "Title": "QA Lead", "ManagerId": 8 },
    { "Id": 31, "Name": "Victoria Turner", "Title": "Marketing Director", "ManagerId": 1 },
    { "Id": 32, "Name": "Jackson Phillips", "Title": "Content Strategist", "ManagerId": 31 },
    { "Id": 33, "Name": "Ella Walker", "Title": "Social Media Manager", "ManagerId": 31 },
    { "Id": 34, "Name": "Grace Carter", "Title": "SEO Specialist", "ManagerId": 31 },
    { "Id": 35, "Name": "Mason Gonzalez", "Title": "Event Coordinator", "ManagerId": 31 },
    { "Id": 36, "Name": "Chloe Ramirez", "Title": "Graphic Designer", "ManagerId": 31 },
    { "Id": 37, "Name": "William Wright", "Title": "Lead Developer", "ManagerId": 3 },
    { "Id": 38, "Name": "Aiden Wood", "Title": "Infrastructure Engineer", "ManagerId": 37 },
    { "Id": 39, "Name": "Lucas James", "Title": "Network Engineer", "ManagerId": 37 },
    { "Id": 40, "Name": "Charlotte Bennett", "Title": "System Administrator", "ManagerId": 38 },
    { "Id": 41, "Name": "James Gray", "Title": "Database Administrator", "ManagerId": 38 },
    { "Id": 42, "Name": "Amelia Wilson", "Title": "Customer Support", "ManagerId": 21 },
    { "Id": 43, "Name": "Isla Harris", "Title": "Support Specialist", "ManagerId": 42 },
    { "Id": 44, "Name": "Olivia Torres", "Title": "Client Success Manager", "ManagerId": 23 },
    { "Id": 45, "Name": "Alexander Powell", "Title": "Field Technician", "ManagerId": 5 },
    { "Id": 46, "Name": "Sophia Morgan", "Title": "Analytics Lead", "ManagerId": 19 },
    { "Id": 47, "Name": "Benjamin Hughes", "Title": "Research Scientist", "ManagerId": 19 },
    { "Id": 48, "Name": "Jack Stewart", "Title": "Intern", "ManagerId": 47 },
    { "Id": 49, "Name": "Henry Jenkins", "Title": "Performance Analyst", "ManagerId": 2 },
    { "Id": 50, "Name": "Emily Peterson", "Title": "Budget Analyst", "ManagerId": 2 },
]